listener 1883
protocol mqtt

allow_anonymous true

persistence true
persistence_location /mosquitto/data/
autosave_interval 1800
autosave_on_changes false

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type all
log_timestamp_format %Y-%m-%dT%H:%M:%S

max_keepalive 600
max_inflight_messages 20
max_queued_messages 1000
retry_interval 20

sys_interval 60
